---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  name: run-shell-script-test
spec:
  steps:
  - name: run-script
    image: alpine:3.12
    script: |
      #!/bin/sh
      echo "Running shell script"
      echo "Hello from the shell script"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  name: shell-script-pipeline-test
spec:
  tasks:
  - name: run-script
    taskRef:
      name: run-shell-script-test
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: pipeline-template-test
spec:
  # params: 
  # - name: gitrevision
  #   description: The git revision
  # - name: gitrepositoryurl
  #   description: The git repository URL
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: shell-script-pipeline-test-run-
    spec:
      pipelineRef:
        name: shell-script-pipeline-test
      resources: []
      params: []
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: trigger-test
spec:
  interceptors:
  - ref:
      name: "cel"
  #   params:
  #   - name: "filter"
  #     value: "header.match('X-GitHub-Event', 'pull_request')"
  #   - name: "overlays"
  #     value:
  #     - key: extensions.truncated_sha
  #       expression: "body.pull_request.head.sha.truncate(7)"
  # bindings:
  # - ref: pipeline-binding
  template:
    ref: pipeline-template-test
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  name: el-shell-script-test
spec:
  serviceAccountName: tekton-webhook-service-account
  triggers:
  - triggerRef: trigger-test
    # bindings:
    # - name: git-pipeline-binding
    #   value: i-called
    # template:
    #   ref: pipeline-template-test
    # interceptors:
    # - ref:
    #     name: "cel"
    #   params:
    #   - name: "filter"
    #     value: "header.match('X-GitHub-Event', 'push')"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  name: el-shell-script-svc
spec:
  # type: NodePort
  selector:
    eventlistener: el-shell-script-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080



