
# PERMISSIONS
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-example-sa
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-example-eventlistener-binding
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: tekton-triggers-example-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-example-eventlistener-clusterbinding
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: tekton-triggers-example-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles

# PIPELINES....
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  steps:
  - name: "echo-test-1"
    image: alpine:3.12
    script: |
      #!/bin/sh
      echo "Running shell script 1"
      sleep 30
      echo "Hello from the shell script 1"
      sleep 30
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # serviceAccountName: tekton-webhook-service-account
  serviceAccountName: tekton-triggers-example-sa
  triggers:
  - name: "test-trigger-task-1"
    bindings:
    - kind: ClusterTriggerBinding
      name: test-webhook-binding
    template:
      apiVersion: tekton.dev/v1alpha1
      kind: TriggerTemplate
      metadata:
        name: test-task-template
      spec:
        resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: TaskRun
          metadata:
            name: test-task-run
          spec:
            taskRef:
              name: test-task
  - name: "test-trigger-task-2"
    template:
      spec: 
        resourceTemplates:
        - apiVersion: "tekton.dev/v1beta1"
          kind: TaskRun
          metadata:
            generateName: "test-run-2-"
          spec:
            taskSpec:
              steps:
              - name: "echo-test-2"
                image: alpine:3.12
                script: |
                  #!/bin/sh
                  echo "Running shell script 2"
                  sleep 30
                  echo "Hello from the shell script 2"
                  sleep 30
