---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  name: run-shell-script-test
spec:
  steps:
  - name: run-script
    image: alpine:3.12
    script: |
      #!/bin/sh
      echo "Running shell script"
      echo "Hello from the shell script"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  name: shell-script-pipeline-test
spec:
  params:
  - name: message
    description: The message to print
    default: This is the default message
    type: string
  - name: contenttype
    description: The Content-Type of the event
    type: string
  - name: git-url
    description: The Git URL to clone from
  - name: git-revision
    description: The Git revision to clone
  tasks:
  - name: run-script
    taskRef:
      name: run-shell-script-test
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: test-binding
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  params:
  - name: gitrevision
    value: main
  - name: gitrepositoryurl
    value: https://github.com/tektoncd/triggers
  - name: contenttype
    value: $(header.Content-Type)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: test-pipeline-template
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: main
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
    default: text/plain
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-run-
    spec:
      pipelineRef:
        name: shell-script-pipeline-test
      params:
      - name: message
        value: $(tt.params.message)
      - name: contenttype
        value: $(tt.params.contenttype)
      - name: git-revision
        value: $(tt.params.gitrevision)
      - name: git-url
        value: $(tt.params.gitrepositoryurl)
      workspaces:
      - name: git-source
        emptyDir: {}
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-test
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  serviceAccountName: tekton-webhook-service-account
  triggers:
    - name: test-trig
      bindings:
      - ref: test-binding
      template:
        ref: test-pipeline-template
