apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  steps:
  - image: alpine:3.12
    onError: continue
    script: |
      #!/bin/sh
      echo "Running shell script 1"
      sleep 30
      echo "Hello from the shell script 1"
      sleep 30
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-test
spec:
  serviceAccountName: tekton-webhook-service-account
  triggers:
  - name: "test-trigger"
    template:
      spec: 
        resourceTemplates:
        - apiVersion: "tekton.dev/v1beta1"
          kind: TaskRun
          metadata:
            generateName: "test-run-1-"
          spec:
            taskRef:
              name: test-task
        - apiVersion: "tekton.dev/v1beta1"
          kind: TaskRun
          metadata:
            generateName: "test-run-2-"
          spec:
            taskSpec:
              steps:
              - image: alpine:3.12
                script: |
                  #!/bin/sh
                  echo "Running shell script 2"
                  sleep 30
                  echo "Hello from the shell script 2"
                  sleep 30
