---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-test
spec:
  serviceAccountName: tekton-webhook-service-account
  triggers:
  - name: "test-trigger"
    template:
      spec: 
        params:
        - name: "my-param-name"
        resourceTemplates:
        - apiVersion: "tekton.dev/v1beta1"
          kind: TaskRun
          metadata:
            generateName: "test-run-"
          spec:
            taskSpec:
              steps:
              - image: alpine:3.12
                script: |
                  #!/bin/sh
                  echo "Running shell script"
                  sleep 30
                  echo "Hello from the shell script"
                  sleep 30
