# Enable the dashboard via a port forwarder.
# Add traefik-dashboard.example.tld to your hosts file and ensure you forward traffic to the NodePort (using socat, for example)
# Then go the the following URL in your Browser: http://traefik-dashboard.example.tld/dashboard/#/
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik-dashboard.example.tld`)
    entryPoints: ["web"]

# Enable the Ingress class
ingressClass:
  name: traefik
providers:
  kubernetesCRD:
    ingressClass: traefik
  kubernetesIngress:
    ingressClass: traefik

# Use NodePort instead of LoadBalancer
service:
  type: NodePort
