# IMPORTANT !!!
#
#   This configuration is for lab purposes and must be considered insecure
#
#   DO NOT USE ON PRODUCTION OR INTERNET FACING SYSTEMS
#
# DOCS:
#   https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md
#   https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md

# Enable the dashboard via a port forwarder.
# Add traefik-dashboard.example.tld to your hosts file and ensure you forward traffic to the NodePort (using socat, for example)
# Then go the the following URL in your Browser: http://traefik-dashboard.example.tld/dashboard/#/
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik-dashboard.example.tld`)
    entryPoints: ["web"]

# Enable the Ingress class
ingressClass:
  name: traefik
providers:
  kubernetesCRD:
    ingressClass: traefik
  kubernetesIngress:
    ingressClass: traefik

# Use NodePort instead of LoadBalancer
service:
  type: NodePort

# Enable access logs
logs:
  access:
    enabled: true
  general:
    level: DEBUG

# Do not check certificates
ports:
  web:
    proxyProtocol:
      insecure: true

# The following allows us to skip TLS/HTTPS certificate verification. It's similar to "curl -k"
# It's ok for a LAB environment, but definitely DO NOT USE THIS IN PRODUCTION OR INTERNET EXPOSED SYSTEMS
additionalArguments:
- --serverstransport.insecureskipverify=true
- --providers.http.tls.insecureskipverify=true
