---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tmp-admin-sa
  namespace: exp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-sa-binding-for-jobs
  namespace: exp
subjects:
- kind: ServiceAccount
  name: tmp-admin-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: reset-dbs-job
  namespace: exp
spec:
  template:
    spec:
      serviceAccountName: tmp-admin-sa
      containers:
      - name: reset-dbs
        image: ghcr.io/nicc777/container-python4aws:v3.12.3-3
        env:
        - name: DEBUG
          value: "1"
        - name: VALKEY_DBS_JSON
          value: '[{"host": "valkey-backend-primary", "port": 6379}, {"host": "valkey-frontend-primary", "port": 6379}]'
        - name: BACKEND_DB_NAME
          value: "valkey-backend-primary"
        - name: QTY_SKU_RECORDS
          value: "3"
        command: ["/bin/bash"]
        args: ["/tmp/scripts/launcher.sh"]
        volumeMounts:
        - name: reset-dbs-code-vol
          mountPath: "/tmp/code"
          readOnly: true
        - name: launcher-script-vol
          mountPath: "/tmp/scripts"
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: reset-dbs-code-vol
        configMap:
          name: reset-dbs-job-python-cm
          items:
          - key: main.py
            path: main.py
      - name: launcher-script-vol
        configMap:
          name: py-job-launcher-v1-cm
          items:
          - key: launcher.sh
            path: launcher.sh
  backoffLimit: 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: py-job-launcher-v1-cm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  launcher.sh: |
    #!/usr/bin/env bash
    pip3 install confluent-kafka avro-python3 valkey
    echo "STARTING APP..."
    python3 /tmp/code/main.py