---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service-target1
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.applicationNames.target1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service-target2
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.applicationNames.target2 }}
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: demo-app-ingress-service
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  namespace: {{ .Values.namespace }}
spec:
  weighted:
    services:
    - name: demo-app-service-target1
      port: 8080
      weight: {{ .Values.weights.target1 }}
    - name: demo-app-service-target2
      port: 8080
      weight: {{ .Values.weights.target2 }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-demo
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`demo.{{ .Values.baseDomain }}`)
    kind: Rule
    services:
    - name: demo-app-ingress-service
      namespace: {{ .Values.namespace }}
      kind: TraefikService
