---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raw-data-generator-demo-v1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: raw-data-generator-demo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raw-data-generator-demo-v1
  template:
    metadata:
      labels:
        app: raw-data-generator-demo-v1
    spec:
      containers:
      - name: raw-data-generator-demo-v1
        image: ghcr.io/nicc777/container-python4aws:v3.12.3-3
        volumeMounts:
        - name: raw-data-generator-code-vol
          mountPath: "/tmp/code"
          readOnly: true
        - name: launcher-script-vol
          mountPath: "/tmp/scripts"
          readOnly: true
        ports:
        - containerPort: 8080
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/code/main.py
          initialDelaySeconds: 1
          periodSeconds: 1
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/code/main.py
          initialDelaySeconds: 1
          periodSeconds: 1
        command: ["/bin/bash"]
        args: ["/tmp/scripts/launcher.sh"]
      volumes:
      - name: raw-data-generator-code-vol
        configMap:
          name: raw-data-generator-python-cm
          items:
          - key: main.py
            path: main.py
      - name: launcher-script-vol
        configMap:
          name: launcher-script-cm
          items:
          - key: launcher.sh
            path: launcher.sh


