---
apiVersion: v1
kind: ConfigMap
metadata:
  name: launcher-script-cm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  launcher.sh: |
    #!/usr/bin/env bash
    pip3 install confluent-kafka avro-python3
    /bin/sh -c python3 /tmp/main.py