---
apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: test-raw-data
  namespace: confluent
spec:
  data:
    configRef: schema-test-raw-data
    format: avro
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-test-raw-data
  namespace: confluent
data:
  schema: |
    {
      "namespace": "tld.example",
      "type": "record",
        "name": "TestRawData",
        "fields": [
            { "name": "sku", "type": "string" },
            { "name": "manufactured_qty", "type": "int" },
            { "name": "year", "type": "int" },
            { "name": "month", "type": "int" },
            { "name": "day", "type": "int" },
            { "name": "hour", "type": "int" }
        ]
    }